# config.yml
language: en
version: "3.1"

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: RegexEntityExtractor
  patterns:
    - pattern: "[A-Z0-9]{3,10}"
      entity: invoice_number
    - pattern: "[A-Z0-9]{3,10}"
      entity: transaction_id
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 150
  constrain_similarities: true
  entity_recognition: true
  intent_classification: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 150

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 150
- name: RulePolicy
assistant_id: 20250508-121728-glass-cycle